"""add_created_at_to_discovery_log

Revision ID: a4548c7c2326
Revises: b2a66b8b03d6
Create Date: 2026-06-19 21:42:08.141216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a4548c7c2326'
down_revision: Union[str, None] = 'b2a66b8b03d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_discovery_log', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True), schema='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_discovery_log', 'created_at', schema='jobs')
    # ### end Alembic commands ###
