"""Initial schema

Revision ID: a856f8400366
Revises: None
Create Date: 2026-06-17 00:45:14.503454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a856f8400366'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('agent_enabled', sa.Boolean(), nullable=True),
    sa.Column('agent_mode', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('job_discovery_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('crawl_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_found', sa.Numeric(precision=8), nullable=True),
    sa.Column('jobs_new', sa.Numeric(precision=8), nullable=True),
    sa.Column('jobs_updated', sa.Numeric(precision=8), nullable=True),
    sa.Column('jobs_expired', sa.Numeric(precision=8), nullable=True),
    sa.Column('errors', sa.Numeric(precision=8), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='jobs'
    )
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_normalized', sa.String(length=255), nullable=True),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('role_normalized', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('stipend_min_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stipend_max_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('experience_min_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('experience_max_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('job_description_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_description_embedding', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('posting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('freshness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('application_count', sa.Numeric(precision=8), nullable=True),
    sa.Column('job_hash', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_hash'),
    sa.UniqueConstraint('source', 'external_id', name='uq_jobs_source_external'),
    schema='jobs'
    )
    op.create_index('idx_job_postings_skills', 'job_postings', ['required_skills'], unique=False, schema='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_job_postings_company_normalized'), 'job_postings', ['company_normalized'], unique=False, schema='jobs')
    op.create_index(op.f('ix_jobs_job_postings_discovered_at'), 'job_postings', ['discovered_at'], unique=False, schema='jobs')
    op.create_index(op.f('ix_jobs_job_postings_is_active'), 'job_postings', ['is_active'], unique=False, schema='jobs')
    op.create_index(op.f('ix_jobs_job_postings_is_expired'), 'job_postings', ['is_expired'], unique=False, schema='jobs')
    op.create_index(op.f('ix_jobs_job_postings_role_normalized'), 'job_postings', ['role_normalized'], unique=False, schema='jobs')
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=False),
    sa.Column('memory_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('importance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'memory_type', 'memory_key', name='uq_agent_memory_key'),
    schema='agents'
    )
    op.create_index('idx_agent_memory_user_type', 'agent_memory', ['user_id', 'memory_type'], unique=False, schema='agents')
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agents'
    )
    op.create_index('idx_agent_runs_user', 'agent_runs', ['user_id', 'started_at'], unique=False, schema='agents')
    op.create_table('screening_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('answer_source', sa.String(length=50), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_hash', name='uq_screening_answers_hash'),
    schema='agents'
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=True),
    sa.Column('jobs_shortlisted', sa.Integer(), nullable=True),
    sa.Column('jobs_rejected', sa.Integer(), nullable=True),
    sa.Column('applications_started', sa.Integer(), nullable=True),
    sa.Column('applications_submitted', sa.Integer(), nullable=True),
    sa.Column('applications_failed', sa.Integer(), nullable=True),
    sa.Column('interviews_received', sa.Integer(), nullable=True),
    sa.Column('offers_received', sa.Integer(), nullable=True),
    sa.Column('avg_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_source', sa.String(length=50), nullable=True),
    sa.Column('top_company', sa.String(length=255), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('agent_runs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'summary_date', name='uq_daily_summaries_user_date'),
    schema='analytics'
    )
    op.create_table('source_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('jobs_discovered', sa.Integer(), nullable=True),
    sa.Column('jobs_applied', sa.Integer(), nullable=True),
    sa.Column('interviews_received', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'period_start', name='uq_source_performance_user_source_period'),
    schema='analytics'
    )
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='auth'
    )
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'is_read'], unique=False, schema='notifications', postgresql_where='is_read = FALSE')
    op.create_index('idx_notifications_user', 'notifications', ['user_id', 'created_at'], unique=False, schema='notifications')
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('date_achieved', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('current_salary_inr', sa.Integer(), nullable=True),
    sa.Column('profile_summary', sa.Text(), nullable=True),
    sa.Column('profile_embedding', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('profile_completeness_score', sa.Integer(), nullable=True),
    sa.Column('last_embedding_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='profile'
    )
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('education_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('experience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills_used', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_roles', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_companies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('blacklisted_companies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('blacklisted_keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_salary_inr', sa.Integer(), nullable=True),
    sa.Column('max_salary_inr', sa.Integer(), nullable=True),
    sa.Column('preferred_salary_inr', sa.Integer(), nullable=True),
    sa.Column('min_stipend_inr', sa.Integer(), nullable=True),
    sa.Column('preferred_stipend_inr', sa.Integer(), nullable=True),
    sa.Column('remote_preference', sa.String(length=20), nullable=True),
    sa.Column('work_type_preference', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_industries', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('min_match_score', sa.Integer(), nullable=True),
    sa.Column('auto_apply_threshold', sa.Integer(), nullable=True),
    sa.Column('max_applications_per_day', sa.Integer(), nullable=True),
    sa.Column('preferred_sources', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('work_authorization', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='profile'
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('project_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_name', sa.String(length=255), nullable=False),
    sa.Column('resume_type', sa.String(length=50), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills_extracted', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', postgresql.ARRAY(sa.Numeric()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', name='uq_skills_user_skill'),
    schema='profile'
    )
    op.create_table('event_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sheets'
    )
    op.create_table('user_spreadsheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spreadsheet_id', sa.String(length=255), nullable=False),
    sa.Column('spreadsheet_url', sa.Text(), nullable=False),
    sa.Column('sheet_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_initialized', sa.Boolean(), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spreadsheet_id'),
    sa.UniqueConstraint('user_id'),
    schema='sheets'
    )
    op.create_table('written_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sheets'
    )
    op.create_index('idx_written_records_dedup', 'written_records', ['user_id', 'sheet_name', 'record_id'], unique=True, schema='sheets')
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agents.agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='agents'
    )
    op.create_index('idx_agent_logs_level', 'agent_logs', ['log_level', 'created_at'], unique=False, schema='agents')
    op.create_index('idx_agent_logs_user', 'agent_logs', ['user_id', 'created_at'], unique=False, schema='agents')
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agent_decision', sa.String(length=20), nullable=True),
    sa.Column('agent_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('application_url', sa.String(length=2000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_to_submit_seconds', sa.Integer(), nullable=True),
    sa.Column('form_fields_filled', sa.Integer(), nullable=True),
    sa.Column('screening_questions_answered', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_postings.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['profile.resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='applications'
    )
    op.create_index('idx_applications_created', 'applications', ['created_at'], unique=False, schema='applications')
    op.create_index('idx_applications_status', 'applications', ['user_id', 'status'], unique=False, schema='applications')
    op.create_index('idx_applications_user', 'applications', ['user_id'], unique=False, schema='applications')
    op.create_table('resume_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['profile.resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='profile'
    )
    op.create_table('application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='applications'
    )
    op.create_index('idx_application_events_app', 'application_events', ['application_id'], unique=False, schema='applications')
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='applications'
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('offered_salary_inr', sa.Integer(), nullable=True),
    sa.Column('offered_role', sa.String(length=255), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('offer_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='applications'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers', schema='applications')
    op.drop_table('interviews', schema='applications')
    op.drop_index('idx_application_events_app', table_name='application_events', schema='applications')
    op.drop_table('application_events', schema='applications')
    op.drop_table('resume_sections', schema='profile')
    op.drop_index('idx_applications_user', table_name='applications', schema='applications')
    op.drop_index('idx_applications_status', table_name='applications', schema='applications')
    op.drop_index('idx_applications_created', table_name='applications', schema='applications')
    op.drop_table('applications', schema='applications')
    op.drop_index('idx_agent_logs_user', table_name='agent_logs', schema='agents')
    op.drop_index('idx_agent_logs_level', table_name='agent_logs', schema='agents')
    op.drop_table('agent_logs', schema='agents')
    op.drop_index('idx_written_records_dedup', table_name='written_records', schema='sheets')
    op.drop_table('written_records', schema='sheets')
    op.drop_table('user_spreadsheets', schema='sheets')
    op.drop_table('event_queue', schema='sheets')
    op.drop_table('skills', schema='profile')
    op.drop_table('resumes', schema='profile')
    op.drop_table('projects', schema='profile')
    op.drop_table('preferences', schema='profile')
    op.drop_table('experience', schema='profile')
    op.drop_table('education', schema='profile')
    op.drop_table('candidate_profiles', schema='profile')
    op.drop_table('achievements', schema='profile')
    op.drop_index('idx_notifications_user', table_name='notifications', schema='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications', schema='notifications', postgresql_where='is_read = FALSE')
    op.drop_table('notifications', schema='notifications')
    op.drop_table('sessions', schema='auth')
    op.drop_table('password_resets', schema='auth')
    op.drop_table('email_verifications', schema='auth')
    op.drop_table('source_performance', schema='analytics')
    op.drop_table('daily_summaries', schema='analytics')
    op.drop_table('screening_answers', schema='agents')
    op.drop_index('idx_agent_runs_user', table_name='agent_runs', schema='agents')
    op.drop_table('agent_runs', schema='agents')
    op.drop_index('idx_agent_memory_user_type', table_name='agent_memory', schema='agents')
    op.drop_table('agent_memory', schema='agents')
    op.drop_index(op.f('ix_jobs_job_postings_role_normalized'), table_name='job_postings', schema='jobs')
    op.drop_index(op.f('ix_jobs_job_postings_is_expired'), table_name='job_postings', schema='jobs')
    op.drop_index(op.f('ix_jobs_job_postings_is_active'), table_name='job_postings', schema='jobs')
    op.drop_index(op.f('ix_jobs_job_postings_discovered_at'), table_name='job_postings', schema='jobs')
    op.drop_index(op.f('ix_jobs_job_postings_company_normalized'), table_name='job_postings', schema='jobs')
    op.drop_index('idx_job_postings_skills', table_name='job_postings', schema='jobs', postgresql_using='gin')
    op.drop_table('job_postings', schema='jobs')
    op.drop_table('job_discovery_log', schema='jobs')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
