"""add_skipped_failed_to_log

Revision ID: b2a66b8b03d6
Revises: a856f8400366
Create Date: 2026-06-19 21:28:42.434495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'b2a66b8b03d6'
down_revision: Union[str, None] = 'a856f8400366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_application_evidence_app', 'application_evidence', ['application_id'], unique=False, schema='applications')
    op.add_column('job_discovery_log', sa.Column('jobs_skipped', sa.Numeric(precision=8), nullable=True), schema='jobs')
    op.add_column('job_discovery_log', sa.Column('jobs_failed', sa.Numeric(precision=8), nullable=True), schema='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_discovery_log', 'jobs_failed', schema='jobs')
    op.drop_column('job_discovery_log', 'jobs_skipped', schema='jobs')
    op.drop_index('idx_application_evidence_app', table_name='application_evidence', schema='applications')
    # ### end Alembic commands ###
